# ---------------------------------------------
# ⚠️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
# Source: backend/db/schemas/__init__.py, backend/db/data_models/__init__.py
# Generated by: backend/db/scripts/generate_sqlmodel_from_sql.py
# ---------------------------------------------

import enum
from datetime import datetime, timezone
from typing import Any, Optional, cast
from uuid import UUID, uuid4

from sqlalchemy.dialects.postgresql import JSON
from sqlmodel import Column, Enum, Field, SQLModel


def enum_values(enum_class: type[enum.Enum]) -> list[str]:
    """Get values for enum."""
    return [status.value for status in enum_class]


class JobStatus(str, enum.Enum):
    QUEUED = "queued"
    DEQUEUED = "dequeued"
    PROCESSING = "processing"
    DONE = "done"
    ERROR = "error"


class PhotobookStatus(str, enum.Enum):
    DRAFT = "draft"
    PENDING = "pending"
    DELETED = "deleted"
    PERMANENTLY_DELETED = "permanently_deleted"
    PUBLISHED = "published"
    UPLOADING = "uploading"
    UPLOAD_FAILED = "upload_failed"
    READY_FOR_GENERATION = "ready_for_generation"
    GENERATING = "generating"
    GENERATION_FAILED = "generation_failed"


class UserProvidedOccasion(str, enum.Enum):
    WEDDING = "wedding"
    BIRTHDAY = "birthday"
    ANNIVERSARY = "anniversary"
    OTHER = "other"


class DAOAssets(SQLModel, table=True):
    __tablename__ = cast("Any", "assets")
    id: UUID = Field(primary_key=True, default_factory=uuid4)
    user_id: UUID
    asset_key_original: Optional[str] = Field(default=None)
    asset_key_display: Optional[str] = Field(default=None)
    asset_key_llm: Optional[str] = Field(default=None)
    metadata_json: Optional[dict[str, Any]] = Field(default=None, sa_type=JSON)
    created_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    original_photobook_id: Optional[UUID] = Field(default=None)


class DAOJobs(SQLModel, table=True):
    __tablename__ = cast("Any", "jobs")
    id: UUID = Field(primary_key=True, default_factory=uuid4)
    job_type: str
    status: JobStatus = Field(
        sa_column=Column(
            Enum(
                JobStatus,
                name="job_status",
                native_enum=True,
                nullable=False,
                values_callable=enum_values,
            )
        )
    )
    input_payload: Optional[dict[str, Any]] = Field(default=None, sa_type=JSON)
    result_payload: Optional[dict[str, Any]] = Field(default=None, sa_type=JSON)
    error_message: Optional[str] = Field(default=None)
    user_id: Optional[UUID] = Field(default=None)
    photobook_id: Optional[UUID] = Field(default=None)
    created_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    started_at: Optional[datetime] = Field(default=None)
    completed_at: Optional[datetime] = Field(default=None)


class DAOPages(SQLModel, table=True):
    __tablename__ = cast("Any", "pages")
    id: UUID = Field(primary_key=True, default_factory=uuid4)
    photobook_id: Optional[UUID] = Field(default=None)
    page_number: int
    user_message: Optional[str] = Field(default=None)
    layout: Optional[str] = Field(default=None)
    created_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    user_message_alternative_options: Optional[dict[str, Any]] = Field(
        default=None, sa_type=JSON
    )


class DAOPagesAssetsRel(SQLModel, table=True):
    __tablename__ = cast("Any", "pages_assets_rel")
    id: UUID = Field(primary_key=True, default_factory=uuid4)
    page_id: Optional[UUID] = Field(default=None)
    asset_id: Optional[UUID] = Field(default=None)
    order_index: Optional[int] = Field(default=None)
    caption: Optional[str] = Field(default=None)


class DAOPhotobookBookmarks(SQLModel, table=True):
    __tablename__ = cast("Any", "photobook_bookmarks")
    id: UUID = Field(primary_key=True, default_factory=uuid4)
    user_id: UUID
    photobook_id: UUID
    created_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    source: Optional[str] = Field(default=None)


class DAOPhotobooks(SQLModel, table=True):
    __tablename__ = cast("Any", "photobooks")
    id: UUID = Field(primary_key=True, default_factory=uuid4)
    user_id: UUID
    title: str
    caption: Optional[str] = Field(default=None)
    theme: Optional[str] = Field(default=None)
    status: Optional[PhotobookStatus] = Field(
        sa_column=Column(
            Enum(
                PhotobookStatus,
                name="photobook_status",
                native_enum=True,
                nullable=True,
                values_callable=enum_values,
            )
        )
    )
    created_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    updated_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    user_provided_occasion: Optional[UserProvidedOccasion] = Field(
        default=None,
        sa_column=Column(
            Enum(
                UserProvidedOccasion,
                name="user_provided_occasion",
                native_enum=True,
                nullable=True,
                values_callable=enum_values,
            )
        ),
    )
    user_provided_occasion_custom_details: Optional[str] = Field(default=None)
    user_provided_context: Optional[str] = Field(default=None)
    thumbnail_asset_id: Optional[UUID] = Field(default=None)
    deleted_at: Optional[datetime] = Field(default=None)


class DAOUsers(SQLModel, table=True):
    __tablename__ = cast("Any", "users")
    id: UUID = Field(primary_key=True)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    email: Optional[str] = Field(default=None)
    phone: Optional[str] = Field(default=None)
    email_confirmed_at: Optional[datetime] = Field(default=None)
    phone_confirmed_at: Optional[datetime] = Field(default=None)
    name: Optional[str] = Field(default=None)
    role: str
